In [1]:
import pandas as pd 
import numpy as np

In [2]:
dict_data = {'a':1, 'b':2 , 'c':3}

In [3]:
sr = pd.Series(dict_data)

In [4]:
print(type(sr))

<class 'pandas.core.series.Series'>


In [5]:
print('\n')

In [6]:
print(sr)

a    1
b    2
c    3
dtype: int64


In [7]:
ps = pd.DataFrame(sr)

In [8]:
ps

0
a  1
b  2
c  3

In [9]:
ps.columns

RangeIndex(start=0, stop=1, step=1)

In [10]:
ps.index

Index(['a', 'b', 'c'], dtype='object')

In [11]:
import numpy as np

In [13]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b = np.array(range(10))

In [16]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a = np.array([[1,1],[2,2],[3,3]])

In [19]:
a.shape

(3, 2)

In [20]:
a.flatten()

array([1, 1, 2, 2, 3, 3])

In [26]:
a = np.array([1,2,3])
b = np.array([[4,5,6],[7,8,9]])

In [29]:
np.append(a , b).shape

(9,)

In [30]:
np.append([a], b , axis=0).shape

(3, 3)

In [32]:
a = np.array([23 , 45, 67, 7, 2, 30, 34, 82])

In [33]:
a.mean()

36.25

In [35]:
a.max()

82

In [36]:
a.min()

2

In [37]:
a = np.random.randint(1, 99, size=10)

In [38]:
a

array([61, 92, 41, 18, 73, 36, 26, 50, 81, 41])

In [39]:
a.max()

92

In [40]:
a.min()

18

In [41]:
a.mean()


51.9

In [43]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]

In [45]:
b = [[2,2,2],
     [2,2,2],
     [2,2,2]]

In [46]:
a+b

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [2, 2, 2], [2, 2, 2], [2, 2, 2]]

In [47]:
a= np.array( [[1,2,3],
              [4,5,6],
              [7,8,9]])

In [48]:
b= np.array( [[2,2,2],
              [2,2,2],
              [2,2,2]])

In [49]:
a+b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
a/b

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [51]:
a@b

array([[12, 12, 12],
       [30, 30, 30],
       [48, 48, 48]])

In [52]:
a.shape

(3, 3)

In [53]:
b.shape

(3, 3)

In [54]:
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [58]:
np.full((3,3), 2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [59]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
np.arange(0,50, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [62]:
np.linspace(0,20, num=5)

array([ 0.,  5., 10., 15., 20.])

In [63]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [65]:
np.arange(0, 24).reshape(4, 3, 2)

(4, 3, 2)

In [66]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [68]:
a = np.arange(1,31).reshape(3,10)

In [70]:
b = a.reshape(6,5)

In [71]:
c = b.transpose()

In [72]:
c

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [73]:
c.shape

(5, 6)

In [74]:
b.shape

(6, 5)

In [75]:
a = np.arange(0, 6).reshape(3,2)

In [76]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [77]:
a.sum()

15

In [78]:
a.sum(axis = 0)

array([6, 9])

In [80]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [79]:
a.sum(axis = 1)

array([1, 5, 9])

In [82]:
a.min(axis = 1)

array([0, 2, 4])

In [84]:
a.max(axis = 1)

array([1, 3, 5])

In [86]:
a = np.random.randint(1 , 100 , size = 15)

In [87]:
a

array([59, 25, 56, 70, 59, 62, 43, 56, 73, 20, 80, 90, 11,  1, 56])

In [93]:
b = a.reshape(3,5)

In [94]:
b

array([[59, 25, 56, 70, 59],
       [62, 43, 56, 73, 20],
       [80, 90, 11,  1, 56]])

In [92]:
b.max(axis=0)

array([80, 90, 56, 73, 59])

In [95]:
b.max(axis=1)

array([70, 73, 90])

In [96]:
a = np.array([1,2,3])

In [97]:
print(a[0], a[1], a[2])

1 2 3


In [98]:
print(a[-1], a[-2], a[-3])

3 2 1


In [101]:
a = np.arange(1,11)

In [108]:
b = a[1:9:2]

In [109]:
b

array([2, 4, 6, 8])

In [110]:
b = a[5:]

In [111]:
b

array([ 6,  7,  8,  9, 10])

In [112]:
c = a[6:]

In [113]:
c

array([ 7,  8,  9, 10])

In [114]:
d = a[0:3]

In [115]:
d

array([1, 2, 3])

In [118]:
e = a[0::2]

In [119]:
e

array([1, 3, 5, 7, 9])

In [126]:
f = a [: : -2]

In [127]:
f

array([10,  8,  6,  4,  2])

In [128]:
a = np.arange(0, 9).reshape(3, 3)

In [129]:
print(a[0])

[0 1 2]


In [130]:
print(a[:, 0])

[0 3 6]


In [133]:
a[0, 0:2]

array([0, 1])

In [134]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [132]:
print(a[0:2, 0:2])

[[0 1]
 [3 4]]


In [136]:
print(a[1, 1:])

[4 5]


In [137]:
a[1, 1:].shape

(2,)

In [138]:
a = np.arange(16).reshape(4,4)

In [139]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [140]:
b = a[0:, 1 ]

In [141]:
b

array([ 1,  5,  9, 13])

In [144]:
c = a[2, 1:]

In [145]:
c

array([ 9, 10, 11])

In [146]:
d = a[0:2, 0:2]

In [147]:
d

array([[0, 1],
       [4, 5]])

In [148]:
e = a[1:3, 1:3]

In [149]:
e

array([[ 5,  6],
       [ 9, 10]])

In [154]:
f = a[0:2, 0:3]

In [155]:
f

array([[0, 1, 2],
       [4, 5, 6]])

In [156]:
g = a[2:]

In [157]:
g

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [162]:
h = a[1::2, 1:]

In [163]:
h

array([[ 5,  6,  7],
       [13, 14, 15]])

In [164]:
f.flatten()

array([0, 1, 2, 4, 5, 6])

In [165]:
g.flatten()

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [166]:
h.flatten()

array([ 5,  6,  7, 13, 14, 15])

In [170]:
import numpy as np 
np.__version__

'1.23.5'

In [175]:
a = np.array([0,0,0,0,0,0,0,0,0,0])

In [179]:
type(a)

numpy.ndarray

In [177]:
b = np.zeros(10,)

In [180]:
type(b)

numpy.ndarray

In [181]:
n_arr = np.array([1,11], dtype= 'int32')

In [183]:
a = np.arange(1,11)

In [184]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [199]:
b = a[::-1]

In [200]:
b 

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [202]:
c =b.reshape(2,5)

In [203]:
d = c.reshape(5,2)

In [204]:
d

array([[10,  9],
       [ 8,  7],
       [ 6,  5],
       [ 4,  3],
       [ 2,  1]])

In [205]:
a = np.arange(1, 17).reshape(4,4)

In [206]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [210]:
a = np.random.rand(10)

In [211]:
a

array([0.3971559 , 0.40497129, 0.87827608, 0.08592737, 0.76846712,
       0.32399135, 0.92370948, 0.43531611, 0.76135301, 0.92682869])

In [212]:
a.max()

0.9268286866153195

In [213]:
a.min()

0.08592736983640048

In [214]:
a.mean()

0.590599638661492

In [215]:
a = np.full((4,4), 0)

In [216]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [217]:
a[::2, ::2] = 1

In [218]:
a

array([[1, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0]])

In [219]:
a[1::2, 1::2] = 1

In [220]:
a

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [230]:
n = int(input("n:"))
a = np.full((n,n), 0)
for i in range(n):
    for j in range(n):
        if (i+j) % 2 == 0:
           a[i, j] = 1 
      
print(a)


[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [237]:
n = 7
a = np.full((n,n), 0)
for i in range(n):
    for j in range(n):
        if i == j :
            a[i, j] = i+1

print(a)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [235]:
a = np.ones((5,5), dtype = 'int32')

In [236]:
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [261]:
n = 6
a = np.ones((n,n), dtype = 'int32')
for i in range(n):
    for j in range(n):
        if j == 0 : 
         a[i, j] = j
        elif j == 4 :
         a[i, j] = 0
        elif i == 0 :
         a[i, j] = 0
        elif i == 4 :
         a[i, j] = 0
print(a)
        

[[0 0 0 0 0 0]
 [0 1 1 1 0 1]
 [0 1 1 1 0 1]
 [0 1 1 1 0 1]
 [0 0 0 0 0 0]
 [0 1 1 1 0 1]]


In [266]:
n = int(input("n:"))
a = np.full((n,n), 1)
a[1:-1, 1:-1] = 0
print(a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [267]:
n = 5
a = np.full((n,n), 0)
a[1:-1, 1:-1] = 1
print(a)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [271]:
a = np.array([0, 10, 20, 40, 60, 80])

In [273]:
b = a[1:3]

In [274]:
b

array([10, 20])

In [282]:
a = np.array([0, 10, 20, 40, 60, 80], dtype = 'int32')
b = np.array([0,20], dtype = 'int32')
c = [] 

for a_1 in a:
    if a_1 in b:
        c.append(True)
    else:
        c.append(False)
c = np.array(c)
print(c)

[ True False  True False False False]


In [284]:
x = np.array([[10,20,40,60], [10,20,40,40]])
a = x.flatten()

In [292]:
a = np.array([0,10,20,40,60,80])
b = np.array([0,20])

In [294]:
a.shape

(6,)

In [295]:
b.shape

(2,)

In [224]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])